version: '3.4'
services:
  hapi:
    build:
      context: .
      dockerfile: Dockerfile.hapi
    expose:
      - "3000"

  static:
    build:
      context: .
      dockerfile: Dockerfile.static
    depends_on:
      - hapi
    environment:
      NODE_SERVER: hapi
      NODE_PORT: "3000"
    ports:
      - "8888:80"
